#!/bin/bash

clear
echo "SPinfo\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
echo "silahkan pilih sistem operasi anda"
read -p "[android]  |  [linux]  |   [update]
>>" spinput;
case $spinput in

android)
   apt install sox -y

  clear
  play toolstart.mp3
  apt install neofetch -y
  clear

alias del=rm
  alias move=mv 
  alias systeminfo=uname

  {
      for ((i = 10 ; i <= 100 ; i+=20)); do
        sleep 1
        echo $i
      done
  } | whiptail --gauge "Mendapatkan informasi..." 6 60 1


  clear
  neofetch

play toolsend.mp3

;;

linux)

  apt install vlc
  nvlc *toolstart.mp3
  clear
  alias del=rm
  alias move=mv 
  alias systeminfo=uname

  {
      for ((i = 10 ; i <= 150 ; i+=20)); do
        sleep 1
        echo $i
      done
  } | whiptail --gauge "Mendapatkan informasi..." 6 60 1


  sudo lshw

;;

update)

     echo "updating..."
     cd
     git clone https://github.com/afri64/sp/
     cd
     cd sp

     {
      for ((i = 10 ; i <= 100 ; i+=15)); do
        sleep 1
        echo $i
      done
  } | whiptail --gauge "Menginstall update..." 6 60 1
     
    bash spr
esac
